//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogovor
    {
        public int ID_Dogovor { get; set; }
        public Nullable<int> ID_Sotrydnik { get; set; }
        public Nullable<int> ID_Klient { get; set; }
        public Nullable<int> ID_Tyra { get; set; }
        public Nullable<System.DateTime> DataZaklycheniya { get; set; }
        public Nullable<System.DateTime> DataDeistvtya { get; set; }
        public string SpisokYslyg { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Sotrydnik Sotrydnik { get; set; }
        public virtual Tyr Tyr { get; set; }
    }
}
