//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exskyrsia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exskyrsia()
        {
            this.BronirovanieExkyrsii = new HashSet<BronirovanieExkyrsii>();
        }
    
        public int ID_Excyrsii { get; set; }
        public string Nazvanie { get; set; }
        public string Opisanie { get; set; }
        public Nullable<decimal> Stoimost { get; set; }
        public Nullable<System.DateTime> DataExskyrsii { get; set; }
        public string Dlitelnost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BronirovanieExkyrsii> BronirovanieExkyrsii { get; set; }
    }
}
