//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gorod
    {
        public int ID_Gorod { get; set; }
        public Nullable<int> ID_Strana { get; set; }
        public string NazvanieGoroda { get; set; }
        public string OpisanieGoroda { get; set; }
    
        public virtual Strana Strana { get; set; }
    }
}
