//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practica.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BronirovanieExkyrsii> BronirovanieExkyrsii { get; set; }
        public virtual DbSet<BronirovanieTransporta> BronirovanieTransporta { get; set; }
        public virtual DbSet<Dogovor> Dogovor { get; set; }
        public virtual DbSet<Dolshnost> Dolshnost { get; set; }
        public virtual DbSet<Exskyrsia> Exskyrsia { get; set; }
        public virtual DbSet<Gorod> Gorod { get; set; }
        public virtual DbSet<Klient> Klient { get; set; }
        public virtual DbSet<Otel> Otel { get; set; }
        public virtual DbSet<Sotrydnik> Sotrydnik { get; set; }
        public virtual DbSet<Strana> Strana { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Transport> Transport { get; set; }
        public virtual DbSet<Tyr> Tyr { get; set; }
    }
}
