//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otel
    {
        public int ID_Otel { get; set; }
        public Nullable<int> ID_Tyra { get; set; }
        public string NazvanieOtelya { get; set; }
        public Nullable<int> KolVoZvezd { get; set; }
        public string OpisanieOtelya { get; set; }
        public Nullable<decimal> ChenaZaNoch { get; set; }
        public string Adress { get; set; }
    
        public virtual Tyr Tyr { get; set; }
    }
}
