//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tyr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tyr()
        {
            this.Dogovor = new HashSet<Dogovor>();
            this.Otel = new HashSet<Otel>();
        }
    
        public int ID_Tyra { get; set; }
        public Nullable<int> ID_Sotrydnik { get; set; }
        public Nullable<int> ID_Strana { get; set; }
        public string Nazvanie { get; set; }
        public Nullable<System.DateTime> DataOkonchaniya { get; set; }
        public Nullable<System.DateTime> DataNachala { get; set; }
        public Nullable<decimal> Stoimost { get; set; }
        public string ProgrammaTyra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dogovor> Dogovor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Otel> Otel { get; set; }
        public virtual Strana Strana { get; set; }
    }
}
